title: 'Sathya Ram'
default_lang: en
author:
  name: 'Sathya Ram'
  email: sathyatheram@gmail.com
  location: Netherlands
taxonomies:
  - tag
metadata:
  description: 'Webdesign by Sathya Ram'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
subtitle: 'Designer ✧ Developer ✧ Photographer'
websites: 'website box text at the top goes here EDIT CONFIG --> SITE'
graphics: 'graphics box text at the top goes here EDIT CONFIG --> SITE'
photography: 'photography box text at the top goes here EDIT CONFIG --> SITE'
