title: 'Sathya Ram'
default_lang: 'en'
author:
  name: 'Sathya Ram'
  email: 'sathyatheram@gmail.com'
  location: 'United States of America'
taxonomies:
  - tag
metadata:
  description: 'Webdesign by Sathya Ram'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
subtitle: 'Designer ✧ Developer ✧ Photographer'
